#!/usr/bin/env python3
"""Consistency gate between ``requirements-dev.txt`` and its compiled lock.

``requirements-dev.lock`` is generated by ``make lock`` (``uv pip compile``) and
is what CI and ``make setup`` install. Dependabot, however, updates the *input*
file. Without this check a bump would land, the lock would keep the old pin, and
CI would silently install the version the pull request claimed to replace — a
merged no-op that looks applied.

The check is deliberately offline and stdlib-only, so it can run before the
install step it protects. It verifies direct-pin synchronization plus lock
pin/hash completeness; it cannot prove the lock is a faithful regeneration of
its input, which is not decidable without a resolver and a network.

Findings are reported as ``<class>: <detail>`` lines. Exit status: 0 pass,
1 findings, 2 usage/environment/malformed-input error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

INPUT_PATH = "requirements-dev.txt"
LOCK_PATH = "requirements-dev.lock"

# An entry is any line that is neither blank, nor a comment, nor a continuation
# of the entry above it. Detection must NOT require "==": a loosened requirement
# has to become a finding, and a rule that only matched pins would skip it
# silently instead.
#
# Indentation alone does not make a line a continuation. pip strips each line
# before parsing it, so `    ruff>=0.16` installs ruff exactly as an unindented
# line would; treating every indented line as continuation text would let that
# requirement slip past the gate entirely. Only the two shapes uv actually emits
# below an entry — `--hash=`/option continuations and `# via` comments — count.
BLANK_OR_COMMENT_RE = re.compile(r"^\s*(?:#.*)?$")
CONTINUATION_RE = re.compile(r"^[ \t]+(?:--|#)")
PIN_RE = re.compile(r"^([A-Za-z0-9._-]+)\s*==\s*([^ ;\\]+)")
NAME_RE = re.compile(r"^([A-Za-z0-9._-]+)")
NORMALIZE_RE = re.compile(r"[-_.]+")


class CheckError(Exception):
    """Environment, usage, or malformed-input error (exit 2)."""


def is_entry(line: str) -> bool:
    """True when ``line`` starts a requirement rather than continuing one."""
    if BLANK_OR_COMMENT_RE.match(line):
        return False
    return not CONTINUATION_RE.match(line)


def normalize(name: str) -> str:
    """Normalize a distribution name per PEP 503."""
    return NORMALIZE_RE.sub("-", name).lower()


def read_lines(path: Path) -> list[str]:
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as exc:
        raise CheckError(f"{path} not found; run `make lock` to create it") from exc
    except OSError as exc:
        raise CheckError(f"{path} is unreadable: {exc}") from exc


def parse_entries(
    lines: list[str],
) -> tuple[dict[str, str], list[tuple[int, str]], list[str]]:
    """Split ``lines`` into pinned entries, unpinned findings, and hash blocks.

    Returns ``(pins, findings, hash_blocks)`` where ``pins`` maps a normalized
    distribution name to its version, ``findings`` holds ``(index, line)`` pairs
    for entries that are not ``==`` pins, and ``hash_blocks[i]`` is the joined
    continuation text owned by the i-th entry.
    """
    pins: dict[str, str] = {}
    findings: list[tuple[int, str]] = []
    hash_blocks: list[str] = []

    current: list[str] | None = None
    for line in lines:
        if not is_entry(line):
            if current is not None:
                current.append(line)
            continue
        if current is not None:
            hash_blocks.append("\n".join(current))
        current = []
        match = PIN_RE.match(line.strip())
        if match is None:
            findings.append((len(hash_blocks), line.strip()))
            continue
        pins[normalize(match.group(1))] = match.group(2)
    if current is not None:
        hash_blocks.append("\n".join(current))

    return pins, findings, hash_blocks


def run_check(repo: Path) -> list[str]:
    input_lines = read_lines(repo / INPUT_PATH)
    lock_lines = read_lines(repo / LOCK_PATH)

    findings: list[str] = []

    input_pins, input_loose, _ = parse_entries(input_lines)
    for _, line in input_loose:
        findings.append(f"input-unpinned: {INPUT_PATH} requires {line!r}, not an == pin")

    lock_pins, lock_loose, lock_blocks = parse_entries(lock_lines)
    for _, line in lock_loose:
        findings.append(f"unpinned: {LOCK_PATH} entry {line!r} is not an == pin")

    if not lock_pins and not lock_loose:
        raise CheckError(f"{LOCK_PATH} declares no requirements; regenerate it")

    for index, block in enumerate(lock_blocks):
        if "--hash=" in block:
            continue
        name = _entry_name(lock_lines, index)
        findings.append(f"unhashed: {LOCK_PATH} entry {name} carries no --hash=")

    for name, version in sorted(input_pins.items()):
        locked = lock_pins.get(name)
        if locked is None:
            findings.append(
                f"pin-missing: {name}=={version} is in {INPUT_PATH} "
                f"but absent from {LOCK_PATH}"
            )
        elif locked != version:
            findings.append(
                f"pin-mismatch: {name} is {version} in {INPUT_PATH} "
                f"but {locked} in {LOCK_PATH}; run `make lock`"
            )

    return findings


def _entry_name(lines: list[str], index: int) -> str:
    """Return the display name of the index-th entry in ``lines``."""
    seen = -1
    for line in lines:
        if not is_entry(line):
            continue
        seen += 1
        if seen == index:
            match = NAME_RE.match(line.strip())
            return match.group(1) if match else line.strip()
    return f"#{index}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check requirements-dev.lock against requirements-dev.txt."
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="repository root containing both files (default: current directory)",
    )
    args = parser.parse_args(argv)

    repo = Path(args.repo)
    if not repo.is_dir():
        print(f"error: --repo {args.repo!r} is not a directory", file=sys.stderr)
        return 2

    try:
        findings = run_check(repo)
    except CheckError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    for finding in findings:
        print(finding)
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
