#!/usr/bin/env python3
"""Generate the committed manifest rows and skill catalog surfaces.

`installer/registry.py` (SKILLS, PLATFORM_REGISTRY, SHARED_REFERENCES) and
canonical skill frontmatter are the sources of truth. The generator validates
every canonical skill, regenerates manifest.json's files array, replaces the
marker-bounded README catalog, and writes the bundled help catalog from the
same family metadata and frontmatter descriptions. Manifest header fields and
README content outside the markers are preserved.

--check regenerates to memory and fails when any committed surface drifts.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

import yaml

PACK_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PACK_ROOT))

from installer.fileops import atomic_write_text  # noqa: E402
from installer.registry import (  # noqa: E402
    FAMILY_DESCRIPTIONS,
    FAMILY_LABELS,
    GENERATED_REFERENCES,
    IF_ANCHOR_EXISTS,
    PACK_NAME,
    PLATFORM_REGISTRY,
    ROOT,
    SHARED_REFERENCES,
    SKILL_NAMES,
    SKILL_PREFIX,
    SKILL_RUNTIME_PROFILES,
    SKILLS,
    TEMPLATES_SKILLS_DIR,
    USER_SCOPE,
    RuntimeProfile,
    SkillInfo,
    argument_vocabulary_errors,
    arguments_section,
)

MANIFEST_PATH = ROOT / "manifest.json"
README_PATH = ROOT / "README.md"
# Versioned machine-readable registry snapshot consumed by se-review-skills'
# skill_review.py instead of AST-parsing installer/registry.py in reviewed
# checkouts. Bump REGISTRY_SNAPSHOT_SCHEMA_VERSION only alongside the consumer's
# supported set (skill_review.SUPPORTED_REGISTRY_SNAPSHOT_SCHEMA_VERSIONS).
REGISTRY_SNAPSHOT_PATH = ROOT / "generated" / "registry-snapshot.json"
REGISTRY_SNAPSHOT_SCHEMA_VERSION = 1
SKILLS_ROOT = ROOT / TEMPLATES_SKILLS_DIR
GENERATED_SKILLS_DIR = "generated/skills"
CLAUDE_GENERATED_ROOT = ROOT / GENERATED_SKILLS_DIR / "claude"
SHARED_DIR_NAME = "_shared"
# A skill body citation of a shipped reference. The leading class requires an
# alphanumeric first character so documentation placeholders like
# `references/<file>.md` (angle-bracketed) never match and never trip the gate.
CITATION_PATTERN = re.compile(r"references/([A-Za-z0-9][A-Za-z0-9._-]*\.md)")
# Header stamped on every generated Markdown surface this script writes. It is
# a named constant so a test can enumerate templates/ and assert the
# source/generated boundary holds, rather than re-typing the sentence.
DO_NOT_EDIT_MARKER = (
    "<!-- Generated by .github/scripts/generate-skill-surfaces.py; do not edit. -->"
)
GENERATED_REFERENCES_DIR = "generated/references"
HELP_CATALOG_SOURCE = f"{GENERATED_REFERENCES_DIR}/skill-catalog.md"
HELP_CATALOG_PATH = ROOT / HELP_CATALOG_SOURCE
# Every generated reference this script knows how to write. Registration in
# GENERATED_REFERENCES only creates manifest rows; a registered source with no
# writer here ships a row pointing at a file that never exists, and the failure
# surfaces as `error: missing pack template` in a user's install rather than in
# CI. Checking membership instead of file presence keeps a fresh checkout that
# has not generated yet from failing generation.
GENERATED_REFERENCE_WRITERS = frozenset({HELP_CATALOG_SOURCE})
# Where this script is allowed to write. DO_NOT_EDIT_MARKER is an HTML comment,
# so a scan for it can only ever cover Markdown: a generated `.json` or `.toml`
# written under templates/ would pass that scan and still break the boundary.
# Guarding the single write choke point instead covers every format, including
# ones no writer emits yet.
#
# Membership is tested on components anchored to ROOT, so no directory above
# the checkout can decide the verdict. Only a target outside ROOT falls back to
# the whole path — that is the generator's own tests redirecting every output
# constant into a temporary tree, where the tail shape is all that survives.
TEMPLATES_COMPONENT = TEMPLATES_SKILLS_DIR.split("/", 1)[0]
GENERATED_COMPONENT = GENERATED_SKILLS_DIR.split("/", 1)[0]
# Whole-repo artifacts with a marked region this script rewrites in place, as
# opposed to files it owns end to end. Neither can live under generated/.
IN_PLACE_WRITE_NAMES = frozenset({"manifest.json", "README.md"})
README_CATALOG_START = "<!-- SE_SKILL_CATALOG:START -->"
README_CATALOG_END = "<!-- SE_SKILL_CATALOG:END -->"

# Agent artifact kind. Canonical sources are neutral MD + frontmatter under
# templates/agents/; the generator renders one overlay per platform whose
# PlatformInfo.agents_dir is set (Claude MD, Codex TOML). The shared Amp anchor
# has agents_dir=None and therefore receives no agent rows.
AGENTS_SUBDIR = "templates/agents"
AGENTS_ROOT = ROOT / AGENTS_SUBDIR
GENERATED_AGENTS_DIR = "generated/agents"
GENERATED_AGENTS_ROOT = ROOT / GENERATED_AGENTS_DIR
CLAUDE_AGENTS_GENERATED_ROOT = GENERATED_AGENTS_ROOT / "claude"
CODEX_AGENTS_GENERATED_ROOT = GENERATED_AGENTS_ROOT / "codex"
# Canonical frontmatter allowlist; the optional hints are the source of the
# per-platform overlay fields (see design D2).
ALLOWED_AGENT_FRONTMATTER_KEYS = (
    "name",
    "description",
    "tools",
    "model",
    "sandbox_mode",
)

REQUIRED_SECTIONS = (
    "## When to use",
    "## Arguments",
    "## Workflow",
    "## Safety rules",
    "## Final report",
)

ALLOWED_FRONTMATTER_KEYS = ("name", "description")
CLAUDE_FRONTMATTER_KEYS = (
    "name",
    "description",
    "disable-model-invocation",
    "user-invocable",
    "context",
    "model",
    "effort",
)
CLAUDE_MODEL_MAP = {
    "inherit": "inherit",
    "fast": "haiku",
    "balanced": "sonnet",
    "deep": "opus",
}
CLAUDE_MODEL_VALUES = frozenset(CLAUDE_MODEL_MAP.values())
CLAUDE_EFFORT_VALUES = frozenset({"low", "medium", "high", "xhigh"})
# Claude skill frontmatter has no field for the portable "fresh-session" context
# (an independent run without inherited conclusions). context: fork is a
# host-managed isolated subagent that RETURNS to the caller and is not
# interchangeable with fresh-session, so mapping fresh-session -> fork would
# misrepresent the intent. Instead the renderer appends this advisory note to the
# generated overlay body (canonical SKILL.md bodies stay untouched) so the intent
# travels with the skill. The marker comment lets tests and the drift gate pin
# exactly which overlays carry it.
FRESH_SESSION_MARKER = "<!-- generated: runtime-profile fresh-session -->"
FRESH_SESSION_NOTE = f"""\
{FRESH_SESSION_MARKER}
> Runtime profile: **fresh-session**. Run this skill as an independent session —
> do not inherit conclusions, scratchpad state, or prior framing from the calling
> context. Start from the artifact and its evidence alone."""
ALLOWED_RESOURCE_SUFFIXES = {
    "references": ".md",
    "scripts": ".py",
}
DESCRIPTION_PREFIX = "Use when"
DESCRIPTION_MAX_LENGTH = 1024

# Canonical bodies speak in capabilities ("your web search tooling"), not
# tool brand names, so one skill text serves every platform. Lowercase
# dotted paths like `.claude/skills` are allowed; brand words are not.
BANNED_PHRASE_PATTERN = re.compile(
    r"\b(Claude|Cowork|Codex|Copilot|Gemini|ChatGPT|OpenAI|Anthropic|Amp)\b"
)

DEFAULT_MANIFEST_HEADER = {
    "schemaVersion": 1,
    "name": PACK_NAME,
    "version": "0.1.0",
    "license": "MIT",
    "description": (
        "Install user-level knowledge-work skills for personal profiles, "
        "consultation, technical authoring, checkpoint-driven technical "
        "tutorials, timestamped video notes, source watchlists, "
        "destination-neutral capture, "
        "critical checklists, "
        "controlled standard operating procedures, "
        "safe operational runbooks, "
        "evidence-aware stakeholder mapping, "
        "source-bound study guides, "
        "message-evidenced conversation digests, "
        "neutral comparisons, "
        "evidence-traceable diagrams, "
        "auditable extreme distillation, "
        "rubric-driven evaluations, "
        "evidence-backed editorial opportunity ranking, "
        "report-first technical editing, "
        "audience-calibrated explanations, "
        "traceable feedback synthesis, "
        "evidence-backed context handoffs, "
        "preview-first knowledge publishing, "
        "bounded knowledge-system audits, "
        "adaptive mastery learning paths, "
        "source-traceable literature maps, "
        "evidence-linked meeting follow-through, "
        "portable baseline monitoring, "
        "methodologically gated research papers, "
        "outcome-based execution planning, "
        "evidence-linked blameless postmortems, "
        "pre-execution failure stress tests, "
        "source-grounded presentation blueprints, "
        "decision-ready proposal development, "
        "source-faithful destination adaptation, "
        "constructive adversarial reviews, "
        "evidence-led general retrospectives, "
        "evidence-backed personal weekly reviews, "
        "bookmark and action-inbox triage, agendas, research, "
        "fact checks, decisions, status "
        "reports, discovery, briefs, meeting prep, scans, and digests into "
        "agent skill directories."
    ),
}
HEADER_FIELDS = tuple(DEFAULT_MANIFEST_HEADER)


class GenerationError(Exception):
    """Raised for any validation or drift failure; no partial writes."""


def _display(path: Path) -> str:
    """Repo-relative label when possible; sandboxed test trees fall back
    to the absolute path."""
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def parse_frontmatter(text: str, label: str) -> tuple[dict, str]:
    if not text.startswith("---\n"):
        raise GenerationError(f"{label}: missing YAML frontmatter opening '---'")
    end = text.find("\n---\n", len("---\n") - 1)
    if end == -1:
        raise GenerationError(f"{label}: missing YAML frontmatter closing '---'")
    raw = text[len("---\n") : end + 1]
    body = text[end + len("\n---\n") :]
    try:
        data = yaml.safe_load(raw)
    except yaml.YAMLError as error:
        raise GenerationError(f"{label}: invalid frontmatter YAML ({error})") from None
    if not isinstance(data, dict):
        raise GenerationError(f"{label}: frontmatter must be a YAML mapping")
    return data, body


_LINE_SEPARATORS = frozenset({"\u2028", "\u2029"})


def _unrenderable_character(value: str) -> str | None:
    """Name the first character this pack's frontmatter round trip cannot carry.

    `yaml.safe_dump` escapes a control character into a double-quoted scalar and
    folds U+2028/U+2029 onto a continuation line. Either output is outside the
    subset the shipped `skill_review.py` parser accepts, so a description
    carrying one generates cleanly and then breaks the review tool. Refusing it
    here keeps the authoritative grammar inside its own subset; the reciprocity
    group in `tests/test_frontmatter_conformance.py` pins the pairing.
    """

    for character in value:
        if character in _LINE_SEPARATORS:
            return f"the line separator U+{ord(character):04X}"
        if unicodedata.category(character) == "Cc":
            return f"the control character U+{ord(character):04X}"
    return None


def validate_skill(name: str) -> tuple[list[str], dict[str, str] | None]:
    errors: list[str] = []
    skill_dir = SKILLS_ROOT / name
    skill_md = skill_dir / "SKILL.md"
    label = _display(skill_md)
    if not skill_md.is_file():
        return [f"{label}: missing canonical SKILL.md"], None
    text = skill_md.read_text(encoding="utf-8")
    try:
        frontmatter, body = parse_frontmatter(text, label)
    except GenerationError as error:
        return [str(error)], None

    extra_keys = sorted(set(frontmatter) - set(ALLOWED_FRONTMATTER_KEYS))
    if extra_keys:
        errors.append(
            f"{label}: frontmatter keys {extra_keys} are not allowed "
            f"(allowed: {', '.join(ALLOWED_FRONTMATTER_KEYS)})"
        )
    if frontmatter.get("name") != name:
        errors.append(
            f"{label}: frontmatter name {frontmatter.get('name')!r} must equal "
            f"the skill directory name {name!r}"
        )
    description = frontmatter.get("description")
    if not isinstance(description, str) or not description.strip():
        errors.append(f"{label}: frontmatter description is missing or empty")
    else:
        if not description.startswith(DESCRIPTION_PREFIX):
            errors.append(
                f"{label}: description must start with {DESCRIPTION_PREFIX!r}"
            )
        if '"' in description:
            errors.append(f"{label}: description must not contain double quotes")
        if "\n" in description.strip():
            errors.append(f"{label}: description must be a single line")
        unrenderable = _unrenderable_character(description)
        if unrenderable is not None:
            errors.append(
                f"{label}: description must not contain {unrenderable}; "
                "yaml.safe_dump escapes or folds it and the shipped "
                "skill_review.py frontmatter parser refuses the result"
            )
        if len(description) > DESCRIPTION_MAX_LENGTH:
            errors.append(
                f"{label}: description exceeds {DESCRIPTION_MAX_LENGTH} characters"
            )

    if not text.endswith("\n"):
        errors.append(f"{label}: file must end with a newline")
    if not body.lstrip("\n").startswith("# "):
        errors.append(f"{label}: body must open with an H1 title")
    last_index = -1
    for section in REQUIRED_SECTIONS:
        index = body.find(f"\n{section}\n")
        if index == -1:
            errors.append(f"{label}: missing required section {section!r}")
            continue
        if index < last_index:
            errors.append(f"{label}: section {section!r} is out of order")
        last_index = index

    errors.extend(
        argument_vocabulary_errors(label, arguments_section(body))
    )

    banned = sorted({match.group(0) for match in BANNED_PHRASE_PATTERN.finditer(text)})
    if banned:
        errors.append(
            f"{label}: framework-neutrality lint: replace brand names {banned} "
            "with capability phrasing (e.g. 'your web search tooling')"
        )

    for path in sorted(skill_dir.rglob("*")):
        relative = path.relative_to(skill_dir).as_posix()
        if path.is_symlink():
            errors.append(
                f"{label}: unexpected symlink {relative} "
                "(skill payload files and directories must be regular)"
            )
            continue
        if path.is_dir():
            relative_dir = path.relative_to(skill_dir)
            if (
                len(relative_dir.parts) != 1
                or relative_dir.parts[0] not in ALLOWED_RESOURCE_SUFFIXES
            ):
                errors.append(
                    f"{label}: unexpected directory "
                    f"{relative_dir.as_posix()}/ (only references/ and scripts/ "
                    "are shipped in this pack version)"
                )
            continue
        if relative == "SKILL.md":
            continue
        parts = Path(relative).parts
        expected_suffix = (
            ALLOWED_RESOURCE_SUFFIXES.get(parts[0]) if len(parts) == 2 else None
        )
        if expected_suffix is None or path.suffix != expected_suffix:
            errors.append(
                f"{label}: unexpected file {relative} (only SKILL.md, "
                "Markdown under references/, and Python under scripts/ are "
                "shipped in this pack version)"
            )
    metadata = None
    if not errors and isinstance(description, str):
        metadata = {"name": name, "description": description}
    return errors, metadata


def validate_skills() -> dict[str, dict[str, str]]:
    errors: list[str] = []
    metadata: dict[str, dict[str, str]] = {}
    if not SKILLS_ROOT.is_dir():
        raise GenerationError(f"missing skills root {SKILLS_ROOT}")
    actual = sorted(
        entry.name
        for entry in SKILLS_ROOT.iterdir()
        if entry.is_dir() and entry.name != SHARED_DIR_NAME
    )
    registered = sorted(SKILL_NAMES)
    missing_dirs = sorted(set(registered) - set(actual))
    unregistered = sorted(set(actual) - set(registered))
    for name in missing_dirs:
        errors.append(
            f"registry skill {name} has no directory under {TEMPLATES_SKILLS_DIR}/"
        )
    for name in unregistered:
        errors.append(
            f"{TEMPLATES_SKILLS_DIR}/{name}/ is not registered in "
            "installer/registry.py SKILL_NAMES"
        )
        if not name.startswith(SKILL_PREFIX):
            errors.append(
                f"{TEMPLATES_SKILLS_DIR}/{name}/ is missing the "
                f"{SKILL_PREFIX} prefix"
            )

    for name in SKILL_NAMES:
        if name in missing_dirs:
            continue
        skill_errors, skill_metadata = validate_skill(name)
        errors.extend(skill_errors)
        if skill_metadata is not None:
            metadata[name] = skill_metadata

    shared_dir = SKILLS_ROOT / SHARED_DIR_NAME
    shared_sources = set(SHARED_REFERENCES)
    if shared_dir.is_dir():
        for path in sorted(shared_dir.rglob("*")):
            if path.is_dir():
                continue
            relative = path.relative_to(SKILLS_ROOT).as_posix()
            if relative not in shared_sources:
                errors.append(
                    f"{TEMPLATES_SKILLS_DIR}/{relative} is not registered in "
                    "installer/registry.py SHARED_REFERENCES"
                )
    for source in sorted(set(GENERATED_REFERENCES) - GENERATED_REFERENCE_WRITERS):
        errors.append(
            f"generated reference {source} is registered but this script writes "
            "no such surface; add a writer or drop the registration"
        )
    for source, consumers in SHARED_REFERENCES.items():
        source_path = SKILLS_ROOT / source
        if not source_path.is_file():
            errors.append(f"missing shared reference {TEMPLATES_SKILLS_DIR}/{source}")
            continue
        basename = source_path.name
        for consumer in consumers:
            own_copy = SKILLS_ROOT / consumer / "references" / basename
            if own_copy.exists():
                errors.append(
                    f"{TEMPLATES_SKILLS_DIR}/{consumer}/references/{basename} "
                    f"collides with the shared reference fan-out of {source}"
                )

    # Reverse citation-closure. The checks above prove registration -> the file
    # exists and fans out; this proves the reverse, that every references/<b>.md
    # a skill body cites will actually ship to that skill. A citation is closed
    # when the skill owns references/<b>.md or is a registered consumer of a
    # shared or generated source named <b>; the fan-out arm keys on membership,
    # so a generated source counts as delivered even on the bootstrap run that
    # has not written it yet.
    delivered: dict[str, set[str]] = {name: set() for name in SKILL_NAMES}
    for registry in (SHARED_REFERENCES, GENERATED_REFERENCES):
        for source, consumers in registry.items():
            basename = source.rsplit("/", 1)[-1]
            for consumer in consumers:
                delivered.setdefault(consumer, set()).add(basename)
    for name in SKILL_NAMES:
        if name in missing_dirs:
            continue
        skill_dir = SKILLS_ROOT / name
        own_refs = skill_dir / "references"
        if own_refs.is_dir():
            # references/ is flat by contract (validate_skill above rejects any
            # nested directory), and citations are flat references/<basename>.md,
            # so a non-recursive iterdir() over regular files is complete.
            for entry in own_refs.iterdir():
                if entry.is_file():
                    delivered.setdefault(name, set()).add(entry.name)
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        body = skill_md.read_text(encoding="utf-8")
        for basename in sorted(set(CITATION_PATTERN.findall(body))):
            if basename not in delivered.get(name, set()):
                errors.append(
                    f"{TEMPLATES_SKILLS_DIR}/{name}/SKILL.md cites "
                    f"references/{basename} but it will not ship to this skill "
                    f"(no own references/{basename} and no registered "
                    "SHARED_REFERENCES or GENERATED_REFERENCES fan-out); add "
                    "the skill as a consumer of the source in "
                    "installer/registry.py, or "
                    f"provide {TEMPLATES_SKILLS_DIR}/{name}/references/{basename}"
                )

    if errors:
        raise GenerationError(
            "skill validation failed:\n" + "\n".join(f"- {error}" for error in errors)
        )
    return metadata


def claude_frontmatter(
    canonical: dict[str, str], profile: RuntimeProfile
) -> dict[str, object]:
    """Translate one portable profile into verified Claude skill metadata."""

    rendered: dict[str, object] = {
        "name": canonical["name"],
        "description": canonical["description"],
    }
    if profile.invocation == "user-only":
        rendered["disable-model-invocation"] = True
    elif profile.invocation == "automatic":
        rendered["user-invocable"] = False
    elif profile.invocation != "both":
        raise GenerationError(
            f"Claude overlay has unknown invocation mode {profile.invocation!r}"
        )

    if profile.context == "forked":
        rendered["context"] = "fork"
    elif profile.context not in {"inline", "fresh-session"}:
        raise GenerationError(
            f"Claude overlay has unknown context mode {profile.context!r}"
        )

    try:
        model = CLAUDE_MODEL_MAP[profile.model]
    except KeyError:
        raise GenerationError(
            f"Claude overlay has unknown portable model profile {profile.model!r}"
        ) from None
    if model not in CLAUDE_MODEL_VALUES:
        raise GenerationError(f"Claude overlay has unsupported model alias {model!r}")
    if profile.effort not in CLAUDE_EFFORT_VALUES:
        raise GenerationError(
            f"Claude overlay has unsupported effort {profile.effort!r}"
        )
    rendered["model"] = model
    rendered["effort"] = profile.effort

    unsupported = sorted(set(rendered) - set(CLAUDE_FRONTMATTER_KEYS))
    if unsupported:
        raise GenerationError(
            f"Claude overlay produced unsupported frontmatter keys {unsupported}"
        )
    return rendered


def render_claude_skill(
    name: str, canonical_text: str, profile: RuntimeProfile
) -> str:
    """Merge Claude metadata into one canonical skill.

    The canonical body is passed through verbatim, with one deliberate
    exception: a ``fresh-session`` profile has no Claude frontmatter encoding, so
    an advisory ``FRESH_SESSION_NOTE`` is appended to the generated overlay body.
    Canonical ``SKILL.md`` bodies are never modified.
    """

    frontmatter, body = parse_frontmatter(
        canonical_text, f"{TEMPLATES_SKILLS_DIR}/{name}/SKILL.md"
    )
    canonical_keys = set(frontmatter)
    if canonical_keys != set(ALLOWED_FRONTMATTER_KEYS):
        raise GenerationError(
            f"{TEMPLATES_SKILLS_DIR}/{name}/SKILL.md: canonical frontmatter keys "
            f"must be {list(ALLOWED_FRONTMATTER_KEYS)}"
        )
    metadata = claude_frontmatter(frontmatter, profile)
    dumped = yaml.safe_dump(
        metadata,
        allow_unicode=True,
        sort_keys=False,
        width=10000,
    )
    if profile.context == "fresh-session":
        # Separate the note from the body by exactly one blank line, independent
        # of the body's own trailing newlines. Only the body is adjusted; the
        # frontmatter block is left intact. (rstrip is on its own line because a
        # backslash escape is not allowed inside an f-string expression on the
        # supported Python 3.10 floor.)
        trimmed_body = body.rstrip("\n")
        body = f"{trimmed_body}\n\n{FRESH_SESSION_NOTE}\n"
    return f"---\n{dumped}---\n{body}"


def regenerated_claude_skill_texts() -> dict[Path, str]:
    """Return every committed Claude entrypoint keyed by generated path."""

    missing_profiles = sorted(set(SKILL_NAMES) - set(SKILL_RUNTIME_PROFILES))
    unknown_profiles = sorted(set(SKILL_RUNTIME_PROFILES) - set(SKILL_NAMES))
    if missing_profiles or unknown_profiles:
        raise GenerationError(
            "runtime profile coverage differs from SKILL_NAMES: "
            f"missing={missing_profiles}, unknown={unknown_profiles}"
        )
    rendered: dict[Path, str] = {}
    for name in SKILL_NAMES:
        canonical_path = SKILLS_ROOT / name / "SKILL.md"
        try:
            canonical_text = canonical_path.read_text(encoding="utf-8")
        except OSError as error:
            raise GenerationError(
                f"cannot read {_display(canonical_path)}: {error}"
            ) from None
        rendered[CLAUDE_GENERATED_ROOT / name / "SKILL.md"] = render_claude_skill(
            name, canonical_text, SKILL_RUNTIME_PROFILES[name]
        )
    return rendered


def read_committed_claude_skills(
    regenerated: dict[Path, str],
) -> tuple[dict[Path, str | None], dict[Path, str]]:
    """Read expected generated files and inventory stale regular files."""

    if CLAUDE_GENERATED_ROOT.is_symlink():
        raise GenerationError(
            f"generated Claude root must not be a symlink: "
            f"{_display(CLAUDE_GENERATED_ROOT)}"
        )
    committed: dict[Path, str | None] = {}
    for path in regenerated:
        if path.is_symlink():
            raise GenerationError(
                f"generated Claude skill must not be a symlink: {_display(path)}"
            )
        if path.exists() and not path.is_file():
            raise GenerationError(
                f"generated Claude skill must be a regular file: {_display(path)}"
            )
        try:
            committed[path] = (
                path.read_text(encoding="utf-8") if path.is_file() else None
            )
        except OSError as error:
            raise GenerationError(
                f"cannot read generated Claude skill {_display(path)}: {error}"
            ) from None

    expected = set(regenerated)
    unexpected: dict[Path, str] = {}
    if CLAUDE_GENERATED_ROOT.is_dir():
        for path in sorted(CLAUDE_GENERATED_ROOT.rglob("*")):
            if path.is_symlink():
                raise GenerationError(
                    f"generated Claude tree contains a symlink: {_display(path)}"
                )
            if path.is_file() and path not in expected:
                try:
                    unexpected[path] = path.read_text(encoding="utf-8")
                except (OSError, UnicodeError) as error:
                    raise GenerationError(
                        f"cannot read unexpected generated file "
                        f"{_display(path)}: {error}"
                    ) from None
    return committed, unexpected


def skill_payload_files(name: str) -> list[str]:
    """Per-skill shipped file list: SKILL.md first, then sorted resources."""
    skill_dir = SKILLS_ROOT / name
    resources: list[str] = []
    for directory, suffix in ALLOWED_RESOURCE_SUFFIXES.items():
        resource_dir = skill_dir / directory
        if resource_dir.is_symlink() or not resource_dir.is_dir():
            continue
        resources.extend(
            path.relative_to(skill_dir).as_posix()
            for path in resource_dir.glob(f"*{suffix}")
            if path.is_file() and not path.is_symlink()
        )
    resources.sort()
    return ["SKILL.md", *resources]


def agent_names() -> list[str]:
    """Sorted canonical agent names discovered under templates/agents/."""

    if not AGENTS_ROOT.is_dir():
        return []
    return sorted(
        path.stem
        for path in AGENTS_ROOT.glob("*.md")
        if path.is_file() and not path.is_symlink()
    )


def _agent_frontmatter(name: str, canonical_text: str) -> tuple[dict, str]:
    """Parse and allowlist one canonical agent's frontmatter and body."""

    label = f"{AGENTS_SUBDIR}/{name}.md"
    frontmatter, body = parse_frontmatter(canonical_text, label)
    extra_keys = sorted(set(frontmatter) - set(ALLOWED_AGENT_FRONTMATTER_KEYS))
    if extra_keys:
        raise GenerationError(
            f"{label}: frontmatter keys {extra_keys} are not allowed "
            f"(allowed: {', '.join(ALLOWED_AGENT_FRONTMATTER_KEYS)})"
        )
    return frontmatter, body


def validate_agent(name: str) -> list[str]:
    errors: list[str] = []
    agent_md = AGENTS_ROOT / f"{name}.md"
    label = _display(agent_md)
    text = agent_md.read_text(encoding="utf-8")
    try:
        frontmatter, body = parse_frontmatter(text, label)
    except GenerationError as error:
        return [str(error)]

    extra_keys = sorted(set(frontmatter) - set(ALLOWED_AGENT_FRONTMATTER_KEYS))
    if extra_keys:
        errors.append(
            f"{label}: frontmatter keys {extra_keys} are not allowed "
            f"(allowed: {', '.join(ALLOWED_AGENT_FRONTMATTER_KEYS)})"
        )
    if frontmatter.get("name") != name:
        errors.append(
            f"{label}: frontmatter name {frontmatter.get('name')!r} must equal "
            f"the agent file stem {name!r}"
        )
    description = frontmatter.get("description")
    if not isinstance(description, str) or not description.strip():
        errors.append(f"{label}: frontmatter description is missing or empty")
    else:
        if '"' in description:
            errors.append(f"{label}: description must not contain double quotes")
        if "\n" in description.strip():
            errors.append(f"{label}: description must be a single line")
        if len(description) > DESCRIPTION_MAX_LENGTH:
            errors.append(
                f"{label}: description exceeds {DESCRIPTION_MAX_LENGTH} characters"
            )
    tools = frontmatter.get("tools")
    if tools is not None and not (
        isinstance(tools, list) and all(isinstance(item, str) for item in tools)
    ):
        errors.append(f"{label}: tools hint must be a list of strings")
    for key in ("model", "sandbox_mode"):
        value = frontmatter.get(key)
        if value is not None and not isinstance(value, str):
            errors.append(f"{label}: {key} hint must be a string")

    if not text.endswith("\n"):
        errors.append(f"{label}: file must end with a newline")
    if not body.lstrip("\n").startswith("# "):
        errors.append(f"{label}: body must open with an H1 title")
    banned = sorted(
        {match.group(0) for match in BANNED_PHRASE_PATTERN.finditer(text)}
    )
    if banned:
        errors.append(
            f"{label}: framework-neutrality lint: replace brand names {banned} "
            "with capability phrasing (e.g. 'your web search tooling')"
        )
    return errors


def validate_agents() -> None:
    if not AGENTS_ROOT.is_dir():
        return
    errors: list[str] = []
    for path in sorted(AGENTS_ROOT.iterdir()):
        if path.is_dir():
            errors.append(
                f"{AGENTS_SUBDIR}/{path.name}/ is unexpected "
                "(only flat *.md agent sources are shipped in this pack version)"
            )
            continue
        if path.is_symlink() or path.suffix != ".md" or not path.is_file():
            errors.append(
                f"{_display(path)} is unexpected (only regular *.md agent "
                "sources are shipped in this pack version)"
            )
    for name in agent_names():
        errors.extend(validate_agent(name))
    if errors:
        raise GenerationError(
            "agent validation failed:\n"
            + "\n".join(f"- {error}" for error in errors)
        )


def validate_delegation_roles(
    profiles: "dict[str, RuntimeProfile] | None" = None,
    known_agents: "set[str] | None" = None,
) -> None:
    """Every delegation role a runtime profile names must resolve to an agent.

    The registry cannot check this itself (it has no agent inventory), so the
    generator owns the cross-check. ``profiles``/``known_agents`` are injectable
    for tests; both default to the live registry map and discovered agents.
    """

    if profiles is None:
        profiles = SKILL_RUNTIME_PROFILES
    if known_agents is None:
        known_agents = set(agent_names())
    errors: list[str] = []
    for skill_name, profile in profiles.items():
        for role in profile.roles:
            if role not in known_agents:
                errors.append(
                    f"skill {skill_name!r} delegation role {role!r} does not "
                    "resolve to a canonical agent under templates/agents/"
                )
    if errors:
        raise GenerationError(
            "delegation role validation failed:\n"
            + "\n".join(f"- {error}" for error in errors)
        )


def _toml_basic_string(value: str) -> str:
    """Encode a scalar as a TOML single-line basic string with full escaping."""

    out: list[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _toml_multiline_string(value: str) -> str:
    """Encode a body as a TOML multiline basic string.

    Every double quote is escaped, so no accidental ``\"\"\"`` can terminate the
    string early; backslashes are doubled; newlines and tabs stay literal. A
    newline is emitted right after the opening delimiter (TOML trims exactly one
    such newline), so the body is preserved byte-for-byte on parse.
    """

    out: list[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch in ("\n", "\t"):
            out.append(ch)
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"""\n' + "".join(out) + '"""'


def render_claude_agent(name: str, canonical_text: str) -> str:
    """Near-passthrough MD overlay: keep portable keys Claude reads, drop the
    Codex-only ``sandbox_mode`` hint, keep the body verbatim."""

    frontmatter, body = _agent_frontmatter(name, canonical_text)
    metadata: dict[str, object] = {
        "name": frontmatter["name"],
        "description": frontmatter["description"],
    }
    for key in ("tools", "model"):
        if key in frontmatter:
            metadata[key] = frontmatter[key]
    dumped = yaml.safe_dump(
        metadata,
        allow_unicode=True,
        sort_keys=False,
        width=10000,
    )
    return f"---\n{dumped}---\n{body}"


def render_codex_agent(name: str, canonical_text: str) -> str:
    """Transform the canonical MD into Codex agent TOML: scalar fields first,
    then the body as ``developer_instructions``."""

    frontmatter, body = _agent_frontmatter(name, canonical_text)
    lines = [
        f"name = {_toml_basic_string(frontmatter['name'])}",
        f"description = {_toml_basic_string(frontmatter['description'])}",
    ]
    for key in ("model", "sandbox_mode"):
        if key in frontmatter:
            lines.append(f"{key} = {_toml_basic_string(frontmatter[key])}")
    lines.append(
        f"developer_instructions = {_toml_multiline_string(body)}"
    )
    return "\n".join(lines) + "\n"


def _agent_generated_path(platform: str, name: str) -> tuple[Path, str]:
    """Return the generated overlay path and manifest source for one agent."""

    if platform == "codex":
        source = f"{GENERATED_AGENTS_DIR}/codex/{name}.toml"
        return CODEX_AGENTS_GENERATED_ROOT / f"{name}.toml", source
    source = f"{GENERATED_AGENTS_DIR}/claude/{name}.md"
    return CLAUDE_AGENTS_GENERATED_ROOT / f"{name}.md", source


def regenerated_agent_texts() -> dict[Path, str]:
    """Every committed agent overlay keyed by its generated path."""

    rendered: dict[Path, str] = {}
    for name in agent_names():
        canonical_path = AGENTS_ROOT / f"{name}.md"
        try:
            canonical_text = canonical_path.read_text(encoding="utf-8")
        except OSError as error:
            raise GenerationError(
                f"cannot read {_display(canonical_path)}: {error}"
            ) from None
        for platform, info in PLATFORM_REGISTRY.items():
            if info.agents_dir is None:
                continue
            path, _ = _agent_generated_path(platform, name)
            if platform == "codex":
                rendered[path] = render_codex_agent(name, canonical_text)
            else:
                rendered[path] = render_claude_agent(name, canonical_text)
    return rendered


def read_committed_agents(
    regenerated: dict[Path, str],
) -> tuple[dict[Path, str | None], dict[Path, str]]:
    """Read expected agent overlays and inventory stale generated files."""

    if GENERATED_AGENTS_ROOT.is_symlink():
        raise GenerationError(
            f"generated agents root must not be a symlink: "
            f"{_display(GENERATED_AGENTS_ROOT)}"
        )
    committed: dict[Path, str | None] = {}
    for path in regenerated:
        if path.is_symlink():
            raise GenerationError(
                f"generated agent must not be a symlink: {_display(path)}"
            )
        if path.exists() and not path.is_file():
            raise GenerationError(
                f"generated agent must be a regular file: {_display(path)}"
            )
        try:
            committed[path] = (
                path.read_text(encoding="utf-8") if path.is_file() else None
            )
        except OSError as error:
            raise GenerationError(
                f"cannot read generated agent {_display(path)}: {error}"
            ) from None

    expected = set(regenerated)
    unexpected: dict[Path, str] = {}
    if GENERATED_AGENTS_ROOT.is_dir():
        for path in sorted(GENERATED_AGENTS_ROOT.rglob("*")):
            if path.is_symlink():
                raise GenerationError(
                    f"generated agents tree contains a symlink: {_display(path)}"
                )
            if path.is_file() and path not in expected:
                try:
                    unexpected[path] = path.read_text(encoding="utf-8")
                except (OSError, UnicodeError) as error:
                    raise GenerationError(
                        f"cannot read unexpected generated file "
                        f"{_display(path)}: {error}"
                    ) from None
    return committed, unexpected


def build_agent_rows() -> list[dict]:
    """One manifest row per (agent, platform-with-agents_dir)."""

    rows: list[dict] = []
    for name in agent_names():
        for platform in sorted(PLATFORM_REGISTRY):
            info = PLATFORM_REGISTRY[platform]
            if info.agents_dir is None:
                continue
            path, source = _agent_generated_path(platform, name)
            rows.append(
                {
                    "platform": platform,
                    "kind": "agent",
                    "scope": USER_SCOPE,
                    "source": source,
                    "target": f"{info.agents_dir}/{path.name}",
                    "anchor": info.anchor,
                    "install": IF_ANCHOR_EXISTS,
                }
            )
    return rows


def build_rows() -> list[dict]:
    rows: list[dict] = []
    for name in SKILL_NAMES:
        payload = skill_payload_files(name)
        # Shared sources are keyed relative to templates/skills/, generated ones
        # repo-relative, so each row's source is built from its own registry
        # rather than from one merged mapping.
        shared = [
            f"{TEMPLATES_SKILLS_DIR}/{source}"
            for source, consumers in SHARED_REFERENCES.items()
            if name in consumers
        ] + [
            source
            for source, consumers in GENERATED_REFERENCES.items()
            if name in consumers
        ]
        for platform in sorted(PLATFORM_REGISTRY):
            info = PLATFORM_REGISTRY[platform]
            for relative in payload:
                source = f"{TEMPLATES_SKILLS_DIR}/{name}/{relative}"
                if platform == "claude" and relative == "SKILL.md":
                    source = f"{GENERATED_SKILLS_DIR}/claude/{name}/SKILL.md"
                rows.append(
                    {
                        "platform": platform,
                        "kind": "skill",
                        "scope": USER_SCOPE,
                        "source": source,
                        "target": f"{info.skills_dir}/{name}/{relative}",
                        "anchor": info.anchor,
                        "install": IF_ANCHOR_EXISTS,
                    }
                )
            for source in shared:
                basename = Path(source).name
                rows.append(
                    {
                        "platform": platform,
                        "kind": "skill",
                        "scope": USER_SCOPE,
                        "source": source,
                        "target": f"{info.skills_dir}/{name}/references/{basename}",
                        "anchor": info.anchor,
                        "install": IF_ANCHOR_EXISTS,
                    }
                )

    rows.extend(build_agent_rows())

    seen: dict[str, str] = {}
    for row in rows:
        key = row["target"].casefold()
        if key in seen:
            raise GenerationError(
                f"duplicate manifest target {row['target']} "
                f"(also produced as {seen[key]})"
            )
        seen[key] = row["target"]
    return rows


def is_derived_row(row: dict) -> bool:
    source = str(row.get("source", ""))
    return source.startswith(
        (
            f"{TEMPLATES_SKILLS_DIR}/",
            f"{GENERATED_SKILLS_DIR}/",
            f"{GENERATED_AGENTS_DIR}/",
            f"{GENERATED_REFERENCES_DIR}/",
        )
    )


def regenerated_manifest_text() -> str:
    if MANIFEST_PATH.is_file():
        try:
            current = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        except (OSError, ValueError) as error:
            raise GenerationError(f"cannot read manifest.json: {error}") from None
        if not isinstance(current, dict):
            raise GenerationError("manifest.json must be a JSON object")
    else:
        current = dict(DEFAULT_MANIFEST_HEADER)

    manifest: dict = {}
    for field in HEADER_FIELDS:
        manifest[field] = current.get(field, DEFAULT_MANIFEST_HEADER[field])
    unknown_header_fields = sorted(set(current) - {*HEADER_FIELDS, "files"})
    if unknown_header_fields:
        raise GenerationError(
            f"manifest.json has unknown header fields {unknown_header_fields}; "
            "extend the generator before adding header fields"
        )

    existing_files = current.get("files", [])
    if not isinstance(existing_files, list):
        raise GenerationError("manifest.json 'files' must be an array")
    static_rows = [
        row
        for row in existing_files
        if isinstance(row, dict) and not is_derived_row(row)
    ]
    manifest["files"] = [*static_rows, *build_rows()]
    return json.dumps(manifest, indent=2) + "\n"


def regenerated_registry_snapshot_text() -> str:
    """Serialize the registry facts skill_review reconstructs, from the real
    imported objects (authoritative). Field ordering is load-bearing: it must
    match _parse_registry so a snapshot-derived RegistryData is byte-identical
    to the AST-derived one (skills in SKILLS order, familyOrder in FAMILY_LABELS
    order, platforms sorted, sharedReferences in SHARED_REFERENCES order)."""
    payload = {
        "schemaVersion": REGISTRY_SNAPSHOT_SCHEMA_VERSION,
        "familyOrder": list(FAMILY_LABELS.keys()),
        "skills": [{"name": skill.name, "family": skill.family} for skill in SKILLS],
        "platforms": sorted(PLATFORM_REGISTRY.keys()),
        "sharedReferences": {
            source: list(consumers) for source, consumers in SHARED_REFERENCES.items()
        },
    }
    return json.dumps(payload, indent=2) + "\n"


def _catalog_table_cell(value: str) -> str:
    return value.replace("|", "\\|")


def rendered_skill_catalog(metadata: dict[str, dict[str, str]]) -> str:
    lines: list[str] = []
    for family, label in FAMILY_LABELS.items():
        family_skills: list[SkillInfo] = [
            skill for skill in SKILLS if skill.family == family
        ]
        if not family_skills:
            continue
        if lines:
            lines.append("")
        lines.extend(
            [
                f"### {label}",
                "",
                "| Skill | Use when |",
                "|---|---|",
            ]
        )
        for skill in family_skills:
            try:
                description = metadata[skill.name]["description"]
            except KeyError:
                raise GenerationError(
                    f"validated metadata missing for registry skill {skill.name}"
                ) from None
            lines.append(
                f"| `{skill.name}` | {_catalog_table_cell(description)} |"
            )
    return "\n".join(lines) + "\n"


def _manifest_version(manifest_text: str) -> str:
    try:
        manifest = json.loads(manifest_text)
    except ValueError as error:
        raise GenerationError(f"cannot read manifest version: {error}") from None
    version = manifest.get("version") if isinstance(manifest, dict) else None
    if not isinstance(version, str) or not version.strip():
        raise GenerationError("manifest.json version must be a non-empty string")
    return version


def rendered_help_catalog(
    metadata: dict[str, dict[str, str]], version: str
) -> str:
    lines = [
        DO_NOT_EDIT_MARKER,
        "# SE Skill Catalog",
        "",
        f"Bundled pack version: `{version}`",
        "",
        (
            "This catalog describes skills bundled with this release. Current "
            "session availability must be reconciled separately by `se-help`."
        ),
    ]
    for family, label in FAMILY_LABELS.items():
        try:
            description = FAMILY_DESCRIPTIONS[family]
        except KeyError:
            raise GenerationError(
                f"family description missing for registry family {family}"
            ) from None
        lines.extend(["", f"## {label}", "", description])
        family_skills = [skill for skill in SKILLS if skill.family == family]
        if not family_skills:
            lines.extend(["", "No bundled skills in this release."])
            continue
        lines.extend(["", "| Skill | Use when |", "|---|---|"])
        for skill in family_skills:
            try:
                skill_description = metadata[skill.name]["description"]
            except KeyError:
                raise GenerationError(
                    f"validated metadata missing for registry skill {skill.name}"
                ) from None
            lines.append(
                f"| `{skill.name}` | {_catalog_table_cell(skill_description)} |"
            )
    return "\n".join(lines) + "\n"


def regenerated_help_catalog_text(
    metadata: dict[str, dict[str, str]] | None = None,
    manifest_text: str | None = None,
) -> str:
    if metadata is None:
        metadata = validate_skills()
    if manifest_text is None:
        manifest_text = regenerated_manifest_text()
    return rendered_help_catalog(metadata, _manifest_version(manifest_text))


def read_readme_text() -> str:
    try:
        return README_PATH.read_text(encoding="utf-8")
    except OSError as error:
        raise GenerationError(f"cannot read README.md: {error}") from None


def regenerated_readme_text(
    metadata: dict[str, dict[str, str]] | None = None,
    current: str | None = None,
) -> str:
    if metadata is None:
        metadata = validate_skills()
    if current is None:
        current = read_readme_text()
    if (
        current.count(README_CATALOG_START) != 1
        or current.count(README_CATALOG_END) != 1
    ):
        raise GenerationError(
            "README.md must contain exactly one ordered pair of skill catalog markers"
        )
    start = current.index(README_CATALOG_START) + len(README_CATALOG_START)
    end = current.index(README_CATALOG_END)
    if start >= end:
        raise GenerationError(
            "README.md must contain exactly one ordered pair of skill catalog markers"
        )
    catalog = rendered_skill_catalog(metadata).rstrip("\n")
    return f"{current[:start]}\n{catalog}\n{current[end:]}"


def _boundary_parts(path: Path) -> tuple[str, ...]:
    """The path components the write guard is allowed to read.

    Anchored to `ROOT` whenever the target is inside the checkout, so a host
    directory above it named `templates` or `generated` cannot decide the
    verdict — a clone under `~/templates/` would otherwise have every write
    refused, and one under `~/generated/` would have stray writes accepted.
    Targets outside `ROOT` are the generator's own tests redirecting output
    into a temporary tree; there is no repo root to anchor to, so the whole
    path is read and the fixtures mirror the real layout for that reason.
    """
    try:
        return path.relative_to(ROOT).parts
    except ValueError:
        return path.parts


def assert_generated_write_target(path: Path) -> None:
    """Reject a write that would put generator output outside generated/.

    `templates/` is the one place skills are hand-edited, so a generated file
    there invites the edit the next `make generate` discards. This is checked
    at the writer rather than by scanning for the do-not-edit marker, because
    the marker is an HTML comment and cannot appear in a generated `.json` or
    `.toml` at all.
    """
    # Before any boundary rule: `..` survives `PurePath` normalization, so
    # `generated/../docs/stray.md` carries a `generated` component the guard
    # would accept while the OS resolves the write to `docs/`. Nothing the
    # generator builds contains one; refusing is cheaper than proving that
    # stays true. `.` needs no companion check — `PurePath` drops it outright,
    # leaving `Path(".").parts == ()`, which no boundary rule accepts anyway.
    if ".." in path.parts:
        raise GenerationError(
            f"{_display(path)} contains a relative path component; the write "
            f"target must be resolved before the {GENERATED_COMPONENT}/ "
            f"boundary can be decided from it"
        )
    parts = _boundary_parts(path)
    if TEMPLATES_COMPONENT in parts:
        raise GenerationError(
            f"{_display(path)} is generator output under "
            f"{TEMPLATES_COMPONENT}/, the one place skills are hand-edited; "
            f"write it under {GENERATED_COMPONENT}/ instead"
        )
    # The in-place surfaces are two exact paths, not two basenames: matching on
    # the name alone would accept `docs/README.md` anywhere in the tree. Read
    # from the module globals so the sandbox tests, which patch both constants
    # into a temporary tree, still exercise this arm.
    if GENERATED_COMPONENT in parts or path in {MANIFEST_PATH, README_PATH}:
        return
    raise GenerationError(
        f"{_display(path)} is neither under {GENERATED_COMPONENT}/ nor one of "
        f"the in-place surfaces ({', '.join(sorted(IN_PLACE_WRITE_NAMES))})"
    )


def write_generated_surfaces(
    updates: list[tuple[Path, str | None, str | None]],
) -> None:
    # Validate every target before mutating any of them: a refusal discovered
    # midway would leave the tree half-written and rely on rollback to undo it.
    for path, _regenerated, _committed in updates:
        assert_generated_write_target(path)
    written: list[tuple[Path, str | None]] = []
    created_directories: list[Path] = []
    try:
        for path, regenerated, committed in updates:
            if regenerated is None:
                path.unlink()
            else:
                missing_parents: list[Path] = []
                current = path.parent
                while not current.exists():
                    missing_parents.append(current)
                    current = current.parent
                path.parent.mkdir(parents=True, exist_ok=True)
                created_directories.extend(reversed(missing_parents))
                atomic_write_text(path, regenerated)
            written.append((path, committed))
    except (OSError, SystemExit) as error:
        rollback_errors: list[str] = []
        for path, committed in reversed(written):
            try:
                if committed is None:
                    path.unlink(missing_ok=True)
                else:
                    atomic_write_text(path, committed)
            except (OSError, SystemExit) as rollback_error:
                rollback_errors.append(f"{_display(path)}: {rollback_error}")
        for directory in reversed(created_directories):
            try:
                directory.rmdir()
            except FileNotFoundError:
                pass
            except OSError:
                if directory.exists():
                    rollback_errors.append(
                        f"{_display(directory)}: could not remove created directory"
                    )
        detail = str(error).removeprefix("error: ")
        if rollback_errors:
            detail += "; rollback failed for " + ", ".join(rollback_errors)
        raise GenerationError(detail) from None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate skills and regenerate manifest and README surfaces."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when a committed generated surface drifts.",
    )
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    try:
        metadata = validate_skills()
        validate_agents()
        validate_delegation_roles()
        regenerated_claude = regenerated_claude_skill_texts()
        committed_claude, unexpected_claude = read_committed_claude_skills(
            regenerated_claude
        )
        regenerated_agents = regenerated_agent_texts()
        committed_agents, unexpected_agents = read_committed_agents(
            regenerated_agents
        )
        regenerated_manifest = regenerated_manifest_text()
        committed_readme = read_readme_text()
        regenerated_readme = regenerated_readme_text(metadata, committed_readme)
        regenerated_help_catalog = regenerated_help_catalog_text(
            metadata, regenerated_manifest
        )
        regenerated_registry_snapshot = regenerated_registry_snapshot_text()
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    try:
        committed_manifest = (
            MANIFEST_PATH.read_text(encoding="utf-8")
            if MANIFEST_PATH.is_file()
            else None
        )
        committed_help_catalog = (
            HELP_CATALOG_PATH.read_text(encoding="utf-8")
            if HELP_CATALOG_PATH.is_file()
            else None
        )
        committed_registry_snapshot = (
            REGISTRY_SNAPSHOT_PATH.read_text(encoding="utf-8")
            if REGISTRY_SNAPSHOT_PATH.is_file()
            else None
        )
    except OSError as error:
        print(f"error: cannot read generated surface: {error}", file=sys.stderr)
        return 1
    if args.check:
        drifted = False
        if committed_manifest != regenerated_manifest:
            print(
                "error: manifest.json drifts from the generated surfaces; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        if committed_readme != regenerated_readme:
            print(
                "error: README.md skill catalog drifts from the generated surfaces; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        if committed_help_catalog != regenerated_help_catalog:
            print(
                "error: skill-catalog.md drifts from the generated surfaces; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        if committed_registry_snapshot != regenerated_registry_snapshot:
            print(
                "error: registry-snapshot.json drifts from installer/registry.py; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        for path, regenerated in regenerated_claude.items():
            if committed_claude[path] != regenerated:
                print(
                    f"error: {_display(path)} drifts from its canonical skill and "
                    "runtime profile; run `make generate` and commit the result",
                    file=sys.stderr,
                )
                drifted = True
        for path in unexpected_claude:
            print(
                f"error: unexpected generated Claude skill {_display(path)}; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        for path, regenerated in regenerated_agents.items():
            if committed_agents[path] != regenerated:
                print(
                    f"error: {_display(path)} drifts from its canonical agent; "
                    "run `make generate` and commit the result",
                    file=sys.stderr,
                )
                drifted = True
        for path in unexpected_agents:
            print(
                f"error: unexpected generated agent {_display(path)}; "
                "run `make generate` and commit the result",
                file=sys.stderr,
            )
            drifted = True
        if drifted:
            return 1
        print(
            "manifest.json, README.md, skill-catalog.md, registry-snapshot.json, "
            "Claude skills, and agent overlays match the generated surfaces"
        )
        return 0

    updates: list[tuple[Path, str | None, str | None]] = []
    if committed_readme != regenerated_readme:
        updates.append((README_PATH, regenerated_readme, committed_readme))
    if committed_help_catalog != regenerated_help_catalog:
        updates.append(
            (
                HELP_CATALOG_PATH,
                regenerated_help_catalog,
                committed_help_catalog,
            )
        )
    for path, regenerated in regenerated_claude.items():
        if committed_claude[path] != regenerated:
            updates.append((path, regenerated, committed_claude[path]))
    for path, committed in unexpected_claude.items():
        updates.append((path, None, committed))
    for path, regenerated in regenerated_agents.items():
        if committed_agents[path] != regenerated:
            updates.append((path, regenerated, committed_agents[path]))
    for path, committed in unexpected_agents.items():
        updates.append((path, None, committed))
    if committed_manifest != regenerated_manifest:
        updates.append((MANIFEST_PATH, regenerated_manifest, committed_manifest))
    if committed_registry_snapshot != regenerated_registry_snapshot:
        updates.append(
            (
                REGISTRY_SNAPSHOT_PATH,
                regenerated_registry_snapshot,
                committed_registry_snapshot,
            )
        )
    if not updates:
        print(
            "manifest.json, README.md, skill-catalog.md, registry-snapshot.json, "
            "Claude skills, and agent overlays unchanged"
        )
        return 0
    try:
        write_generated_surfaces(updates)
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    for path, regenerated, _ in updates:
        action = "removed" if regenerated is None else "wrote"
        print(f"{action} {_display(path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
